### ISSUE TITLE
Fix UI to handle the process of scheduling contests

### ISSUE THREAD

**Issue by kid-116** [kid-116/CPing#37]
## Description
Currently, anytime a user registers an event, the screen fades until the event is registered in their calendar, which results in a poor user experience.

### Task

- The objective is to add a loading widget that overlays the screen.
- Remove the current screen fading that occurs when registering for a contest.

**Comment by Shash0501** [comment]
## Description
Currently, anytime a user registers an event, the screen fades until the event is registered in their calendar, which results in a poor user experience.

### Task

- The objective is to add a loading widget that overlays the screen.
- Remove the current screen fading that occurs when registering for a contest.
