### ISSUE TITLE
Implement new UI design for contest cards

### ISSUE THREAD

**Issue by kid-116** [kid-116/CPing#38]
## Description
Contest cards provide the necessary information for a contest. A precise contest card with a modular design will promote user interaction. As a result, a new contest card design is required, with the design being responsive and accurate.

#### Link to Figma designs
https://www.figma.com/file/TmXK9ZfIX91RZlwguX4O7N/CPing?node-id=0%3A1

**Comment by Shash0501** [comment]
### Description
Contest cards provide the necessary information for a contest. A precise contest card with a modular design will promote user interaction. As a result, a new contest card design is required, with the design being responsive and accurate.

**Comment by FaizFk** [comment]
Hi, Can I do this task.
